[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "stdenv.cc.cc.lib"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "python api_server.py"
