[phases.setup]
nixPkgs = ["python311", "gcc", "stdenv.cc.cc.lib", "curl"]

[phases.install]
cmds = [
    "python -m venv .venv",
    "curl -sS https://bootstrap.pypa.io/get-pip.py | .venv/bin/python",
    ".venv/bin/pip install -r requirements.txt"
]

[start]
cmd = ".venv/bin/python api_server.py"
